# Generated by Django 5.2.4 on 2025-08-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userrole',
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating_value',
            field=models.FloatField(default=0.0),
        ),
    ]
