# Generated by Django 5.2.4 on 2025-08-08 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_user_userrole_user_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Number of passengers the vehicle can carry')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike')], default='Car', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
