# Generated by Django 5.2.4 on 2025-08-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.CharField(help_text='Comma-separated values', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], max_length=20, null=True),
        ),
    ]
