# Generated by Django 5.2.4 on 2025-08-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_vehicle_features_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridedetails',
            name='drive_from',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='drive_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
