# Generated by Django 5.2.4 on 2025-08-12 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ridedetails_drive_from_ridedetails_drive_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find_ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(null=True)),
                ('drop_point', models.CharField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_from', models.CharField(null=True)),
                ('ride_to', models.CharField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
