# Generated by Django 5.2.4 on 2025-08-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_find_ride_offer_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find_ride',
            old_name='rider_id',
            new_name='rider',
        ),
    ]
