# Generated by Django 5.2.4 on 2025-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_rider_id_find_ride_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find_ride',
            name='drop_point',
        ),
        migrations.RemoveField(
            model_name='find_ride',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='ride_from',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='ride_to',
        ),
        migrations.AddField(
            model_name='find_ride',
            name='drop_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='find_ride',
            name='drop_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='find_ride',
            name='pickup_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='find_ride',
            name='pickup_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='from_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='from_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='to_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='to_lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='find_ride',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='find_ride',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
