# Generated by Django 5.2.4 on 2025-08-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_find_ride_drop_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_ride',
            name='route_data',
            field=models.FloatField(null=True),
        ),
    ]
