# Generated by Django 5.2.4 on 2025-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_find_ride_route_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_ride',
            name='route_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
