# Generated by Django 5.2.4 on 2025-08-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_offer_ride_route_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_ride',
            name='available_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.vehicle'),
        ),
    ]
