# Generated by Django 5.2.4 on 2025-08-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_offer_ride_available_seats_offer_ride_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_ride',
            name='required_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='waypoints',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='from_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='from_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='to_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='to_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
