# Generated by Django 5.2.4 on 2025-09-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_find_ride_required_seats_offer_ride_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_ride',
            name='waypoints',
        ),
    ]
