# Generated by Django 5.2.4 on 2025-09-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_offer_ride_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_ride',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
