# Generated by Django 5.2.4 on 2025-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_find_ride_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='milage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='find_ride',
            name='required_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=20),
        ),
    ]
