# Generated by Django 5.2.4 on 2025-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_vehicle_milage_alter_find_ride_required_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find_ride',
            name='required_seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offer_ride',
            name='available_seats',
            field=models.IntegerField(default=1),
        ),
    ]
