# Generated by Django 5.2.4 on 2025-09-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_find_ride_required_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.offer_ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.find_ride')),
            ],
        ),
    ]
