# Generated by Django 5.2.4 on 2025-09-03 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_ridematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridematch',
            name='driver_ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.offer_ride'),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='rider_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.find_ride'),
        ),
        migrations.AlterField(
            model_name='ridematch',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ridematch',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
