# Generated by Django 5.2.4 on 2025-09-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_ridematch_driver_ride_ridematch_rider_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridematch',
            name='driver_ride',
        ),
        migrations.RemoveField(
            model_name='ridematch',
            name='rider_request',
        ),
    ]
