# Generated by Django 5.2.4 on 2025-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_ridematch_driver_ride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridematch',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
