# Generated by Django 5.2.4 on 2025-09-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_ridematch_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find_ride',
            name='route_data',
        ),
    ]
