# Generated by Django 5.2.6 on 2025-09-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_find_ride_route_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find_ride',
            name='drop_lat',
        ),
        migrations.RemoveField(
            model_name='find_ride',
            name='drop_lng',
        ),
        migrations.RemoveField(
            model_name='find_ride',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='find_ride',
            name='pickup_lng',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='from_lat',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='from_lng',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='to_lat',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='to_lng',
        ),
        migrations.RemoveField(
            model_name='ridematch',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='ridematch',
            name='score',
        ),
        migrations.AddField(
            model_name='find_ride',
            name='locations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='locations',
            field=models.JSONField(default=dict),
        ),
    ]
