# Generated by Django 5.2.6 on 2025-09-04 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_find_ride_drop_lat_remove_find_ride_drop_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridematch',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ridematch',
            name='rider',
        ),
        migrations.AddField(
            model_name='ridematch',
            name='find',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='home.find_ride'),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='offer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='home.offer_ride'),
        ),
    ]
