# Generated by Django 5.2.5 on 2025-09-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_ridematch_driver_remove_ridematch_rider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='milage',
            new_name='mileage',
        ),
    ]
