# Generated by Django 5.2.5 on 2025-09-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_milage_vehicle_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridedetails',
            name='drive_from',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='drive_to',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='ridedetails',
            name='route',
        ),
        migrations.AddField(
            model_name='ridedetails',
            name='trip_cost',
            field=models.IntegerField(null=True),
        ),
    ]
