# Generated by Django 5.2.5 on 2025-09-05 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_ridedetails_drive_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ridematch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ridematch'),
        ),
        migrations.RenameField(
            model_name='ridematch',
            old_name='matched_at',
            new_name='matched_on',
        ),
        migrations.RemoveField(
            model_name='ridematch',
            name='find',
        ),
        migrations.AddField(
            model_name='ridematch',
            name='ride_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='rider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ride_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='rider_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ridematch',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ridematch',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_matches', to='home.offer_ride'),
        ),
        migrations.DeleteModel(
            name='RideDetails',
        ),
    ]
