# Generated by Django 5.2.5 on 2025-09-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_feedback_ride_alter_payment_ride_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Find_ride',
        ),
    ]
