# Generated by Django 5.2.5 on 2025-09-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_find_ride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Find_ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.JSONField(default=dict)),
                ('required_seats', models.IntegerField(default=1)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('preferences', models.JSONField(default=dict)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
