# Generated by Django 5.2.5 on 2025-09-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find_ride',
            name='preferences',
        ),
        migrations.AddField(
            model_name='find_ride',
            name='drop_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='find_ride',
            name='pickup_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='drop_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='offer_ride',
            name='pickup_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
