# Generated by Django 5.2.5 on 2025-09-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_find_ride_preferences_find_ride_drop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='segment',
            field=models.CharField(null=True),
        ),
    ]
