# Generated by Django 5.2.5 on 2025-09-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_vehicle_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_ride',
            old_name='drop_name',
            new_name='from_name',
        ),
        migrations.RenameField(
            model_name='offer_ride',
            old_name='pickup_name',
            new_name='to_name',
        ),
    ]
