# Generated by Django 5.2.5 on 2025-09-15 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_drop_name_offer_ride_from_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('drop_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('drop_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ride_date', models.DateField()),
                ('ride_time', models.TimeField()),
                ('seats_booked', models.IntegerField(default=1)),
                ('total_distance', models.FloatField(default=0)),
                ('rider_distance', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('rider_share', models.FloatField(default=0)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_rides', to='home.offer_ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.vehicle')),
            ],
        ),
    ]
