# Generated by Django 5.2.5 on 2025-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_bookedride'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedride',
            name='status',
            field=models.CharField(null=True),
        ),
    ]
