# Generated by Django 5.2.5 on 2025-09-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_bookedride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='find_ride',
            name='status',
            field=models.CharField(default='pending'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_approval',
            field=models.CharField(default='pending'),
        ),
    ]
