# Generated by Django 5.2.5 on 2025-09-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_find_ride_status_vehicle_vehicle_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedride',
            old_name='drop_lat',
            new_name='drop_place',
        ),
        migrations.RenameField(
            model_name='bookedride',
            old_name='drop_lng',
            new_name='pickup_place',
        ),
        migrations.RemoveField(
            model_name='bookedride',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='bookedride',
            name='pickup_lng',
        ),
    ]
