# Generated by Django 5.2.5 on 2025-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_drop_lat_bookedride_drop_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedride',
            old_name='status',
            new_name='driver_status',
        ),
        migrations.AddField(
            model_name='bookedride',
            name='rider_status',
            field=models.CharField(null=True),
        ),
    ]
