# Generated by Django 5.2.5 on 2025-09-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_status_bookedride_driver_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bookedride'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bookedride'),
        ),
        migrations.RemoveField(
            model_name='find_ride',
            name='status',
        ),
        migrations.RemoveField(
            model_name='offer_ride',
            name='preferences',
        ),
        migrations.DeleteModel(
            name='RideMatch',
        ),
    ]
