# Generated by Django 5.2.5 on 2025-09-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_feedback_ride_alter_payment_ride_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedride',
            old_name='preferences',
            new_name='matched_preferences',
        ),
        migrations.AddField(
            model_name='bookedride',
            name='unmatched_preferences',
            field=models.JSONField(default=dict),
        ),
    ]
