# Generated by Django 5.2.5 on 2025-09-26 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_topup',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_topup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
