# Generated by Django 5.2.5 on 2025-09-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_wallet_last_topup_wallet_last_topup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedride',
            name='driver_feedback',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='bookedride',
            name='rider_feedback',
            field=models.CharField(null=True),
        ),
    ]
