# Generated by Django 5.2.6 on 2025-09-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_bookedride_driver_feedback_bookedride_rider_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.CharField(default='no'),
        ),
    ]
