# Generated by Django 5.2.5 on 2025-10-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Find_ride',
        ),
    ]
