# Generated by Django 5.2.5 on 2025-10-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_delete_find_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedride',
            name='cancel_reason',
            field=models.CharField(null=True),
        ),
    ]
