# Generated by Django 5.2.5 on 2025-10-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_bookedride_cancel_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedride',
            name='matched_preferences',
        ),
        migrations.RemoveField(
            model_name='bookedride',
            name='unmatched_preferences',
        ),
    ]
