# Generated by Django 5.2.5 on 2025-10-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_remove_bookedride_matched_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='features',
        ),
    ]
